;<?/*
[conf_host]
site_name="eコミュニティ・プラットフォーム2.0"
publish="1"
site_url="http://localhost/"
url_base="http://localhost"
email="yamada+ecomlocal@kirishikistudios.com"
err_email="yamada+ecomlocalerror@kirishikistudios.com"
smtp_server="localhost"
random_seed="yamadanaoyuki"
passwd="codeforjapan"
[conf_mysql]
server="localhost"
user="ecom"
passwd="ecompasswd"
database="ecom"
[conf_dir]
smarty_compile="_tpl_compile"
smarty_cache="_tpl_cache"
smarty_config="_tpl_config"
databox_urlbase="http://localhost"
databox_dir="databox"
convert_path=""
[conf_map]
api_key="AIzaSyC0NKToO039qtXD6fMJR-X_gs-KkE68Q0s"
longitude="140.1112174987793"
latitude="36.082748448481766"
zoom="15"
;*/?>
